"""
Seed a starter set of exercises for the Exercise Library tab.
Run: python backend/seed_exercise_library.py
"""
from app import app, db
from models import Exercise
import json


SEED_EXERCISES = [
    {
        "category": "bodybuilding_machine",
        "name_fa": "پرس سینه با دستگاه",
        "name_en": "Chest Press Machine",
        "target_muscle_fa": "سینه، شانه، سه‌سر",
        "target_muscle_en": "Chest, shoulders, triceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر را به پشتی بچسبانید و حرکت را کنترل‌شده انجام دهید.",
        "execution_tips_en": "Keep your back on the pad and move under control.",
        "breathing_guide_fa": "دم هنگام پایین آوردن، بازدم هنگام فشار دادن.",
        "breathing_guide_en": "Inhale on the way down, exhale on the press.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "دستگاه پرس سینه",
        "equipment_needed_en": "Chest press machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "زیر بغل سیم‌کش",
        "name_en": "Lat Pulldown",
        "target_muscle_fa": "پشت، زیر بغل، جلو بازو",
        "target_muscle_en": "Lats, back, biceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "سینه را بالا نگه دارید و میله را به سمت سینه بکشید.",
        "execution_tips_en": "Keep chest up and pull the bar to the upper chest.",
        "breathing_guide_fa": "دم هنگام بازگشت، بازدم هنگام کشیدن.",
        "breathing_guide_en": "Inhale on return, exhale as you pull.",
        "injury_contraindications": ["shoulder", "neck"],
        "equipment_needed_fa": "دستگاه سیم‌کش",
        "equipment_needed_en": "Cable machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پرس پا",
        "name_en": "Leg Press",
        "target_muscle_fa": "چهارسر، همسترینگ، باسن",
        "target_muscle_en": "Quads, hamstrings, glutes",
        "level": "beginner",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "زانوها را قفل نکنید و دامنه حرکت کنترل‌شده باشد.",
        "execution_tips_en": "Do not lock knees; keep a controlled range of motion.",
        "breathing_guide_fa": "دم هنگام پایین آوردن، بازدم هنگام فشار دادن.",
        "breathing_guide_en": "Inhale down, exhale as you press.",
        "injury_contraindications": ["knee", "lower_back"],
        "equipment_needed_fa": "دستگاه پرس پا",
        "equipment_needed_en": "Leg press machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "جلو پا دستگاه",
        "name_en": "Leg Extension",
        "target_muscle_fa": "چهارسر",
        "target_muscle_en": "Quadriceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "زانوها را قفل نکنید و حرکت نرم باشد.",
        "execution_tips_en": "Avoid locking knees and keep the motion smooth.",
        "breathing_guide_fa": "بازدم هنگام بالا بردن، دم هنگام بازگشت.",
        "breathing_guide_en": "Exhale up, inhale on return.",
        "injury_contraindications": ["knee"],
        "equipment_needed_fa": "دستگاه جلو پا",
        "equipment_needed_en": "Leg extension machine",
    },
    {
        "category": "functional_home",
        "name_fa": "اسکوات وزن بدن",
        "name_en": "Bodyweight Squat",
        "target_muscle_fa": "چهارسر، باسن، همسترینگ",
        "target_muscle_en": "Quads, glutes, hamstrings",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "زانـوها هم‌راستا با پنجه؛ سینه بالا.",
        "execution_tips_en": "Keep knees aligned with toes and chest up.",
        "breathing_guide_fa": "دم هنگام پایین رفتن، بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["knee", "lower_back"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "پلانک",
        "name_en": "Plank",
        "target_muscle_fa": "عضلات مرکزی",
        "target_muscle_en": "Core",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "بدن را خطی نگه دارید و کمر را نچرخانید.",
        "execution_tips_en": "Keep body in a straight line; avoid hip sag.",
        "breathing_guide_fa": "تنفس آرام و منظم.",
        "breathing_guide_en": "Slow, steady breathing.",
        "injury_contraindications": ["wrist", "lower_back"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "لانژ معکوس",
        "name_en": "Reverse Lunge",
        "target_muscle_fa": "چهارسر، باسن",
        "target_muscle_en": "Quads, glutes",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "گام کوتاه؛ زانوی جلو روی پنجه.",
        "execution_tips_en": "Take a short step; front knee over toes.",
        "breathing_guide_fa": "دم هنگام پایین رفتن، بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["knee", "ankle"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "برپی",
        "name_en": "Burpee",
        "target_muscle_fa": "تمام بدن",
        "target_muscle_en": "Full body",
        "level": "intermediate",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت پیوسته و کنترل‌شده؛ فرود نرم.",
        "execution_tips_en": "Continuous, controlled motion with soft landings.",
        "breathing_guide_fa": "بازدم هنگام جهش، دم هنگام بازگشت.",
        "breathing_guide_en": "Exhale on jump, inhale on return.",
        "injury_contraindications": ["knee", "ankle", "wrist"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "کتل‌بل سوئینگ",
        "name_en": "Kettlebell Swing",
        "target_muscle_fa": "باسن، همسترینگ، پشت",
        "target_muscle_en": "Glutes, hamstrings, back",
        "level": "intermediate",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت از مفصل لگن؛ کمر خنثی.",
        "execution_tips_en": "Drive from hips; keep a neutral back.",
        "breathing_guide_fa": "بازدم در حرکت رو به بالا.",
        "breathing_guide_en": "Exhale on the upward swing.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "کتل‌بل",
        "equipment_needed_en": "Kettlebell",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پرس شانه دستگاه",
        "name_en": "Shoulder Press Machine",
        "target_muscle_fa": "شانه، سه‌سر",
        "target_muscle_en": "Shoulders, triceps",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "آرنج‌ها کمی جلوتر؛ حرکت کنترل‌شده.",
        "execution_tips_en": "Keep elbows slightly forward; controlled motion.",
        "breathing_guide_fa": "بازدم هنگام فشار دادن.",
        "breathing_guide_en": "Exhale on press.",
        "injury_contraindications": ["shoulder", "neck"],
        "equipment_needed_fa": "دستگاه پرس شانه",
        "equipment_needed_en": "Shoulder press machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "قایقی نشسته",
        "name_en": "Seated Row",
        "target_muscle_fa": "پشت، زیر بغل",
        "target_muscle_en": "Back, lats",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "تیغه‌های کتف را جمع کنید.",
        "execution_tips_en": "Squeeze shoulder blades together.",
        "breathing_guide_fa": "بازدم هنگام کشیدن.",
        "breathing_guide_en": "Exhale as you pull.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "دستگاه قایقی",
        "equipment_needed_en": "Seated row machine",
    },
    {
        "category": "functional_home",
        "name_fa": "شنا سوئدی اصلاح‌شده",
        "name_en": "Modified Push-up",
        "target_muscle_fa": "سینه، شانه، پشت بازو",
        "target_muscle_en": "Chest, shoulders, triceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "زانو روی زمین؛ بدن در یک خط.",
        "execution_tips_en": "Knees on floor; keep body aligned.",
        "breathing_guide_fa": "دم هنگام پایین رفتن، بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["wrist", "shoulder"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پرس سینه دمبل",
        "name_en": "Dumbbell Bench Press",
        "target_muscle_fa": "سینه، شانه، سه‌سر",
        "target_muscle_en": "Chest, shoulders, triceps",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "مچ‌ها را صاف نگه دارید و آرنج‌ها ۴۵ درجه باشند.",
        "execution_tips_en": "Keep wrists neutral; elbows at about 45 degrees.",
        "breathing_guide_fa": "دم پایین، بازدم بالا.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "دمبل و نیمکت",
        "equipment_needed_en": "Dumbbells and bench",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "فلای سینه دستگاه",
        "name_en": "Pec Deck Fly",
        "target_muscle_fa": "سینه",
        "target_muscle_en": "Chest",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت را آهسته انجام دهید و کتف‌ها ثابت باشد.",
        "execution_tips_en": "Move slowly; keep shoulders stable.",
        "breathing_guide_fa": "بازدم هنگام جمع کردن دست‌ها.",
        "breathing_guide_en": "Exhale as you bring arms together.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "دستگاه فلای",
        "equipment_needed_en": "Pec deck machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "جلو بازو دمبل تناوبی",
        "name_en": "Alternating Dumbbell Curl",
        "target_muscle_fa": "جلو بازو",
        "target_muscle_en": "Biceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "آرنج‌ها نزدیک بدن؛ حرکت کنترل‌شده.",
        "execution_tips_en": "Keep elbows close; controlled motion.",
        "breathing_guide_fa": "بازدم هنگام بالا آوردن.",
        "breathing_guide_en": "Exhale on the curl.",
        "injury_contraindications": ["wrist"],
        "equipment_needed_fa": "دمبل",
        "equipment_needed_en": "Dumbbells",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "جلو بازو هالتر",
        "name_en": "Barbell Curl",
        "target_muscle_fa": "جلو بازو",
        "target_muscle_en": "Biceps",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر ثابت؛ از تاب دادن پرهیز کنید.",
        "execution_tips_en": "Keep torso still; avoid swinging.",
        "breathing_guide_fa": "بازدم بالا، دم پایین.",
        "breathing_guide_en": "Exhale up, inhale down.",
        "injury_contraindications": ["wrist"],
        "equipment_needed_fa": "هالتر",
        "equipment_needed_en": "Barbell",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پشت بازو سیم‌کش",
        "name_en": "Cable Triceps Pushdown",
        "target_muscle_fa": "پشت بازو",
        "target_muscle_en": "Triceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "آرنج‌ها ثابت؛ فقط ساعد حرکت کند.",
        "execution_tips_en": "Keep elbows fixed; move only forearms.",
        "breathing_guide_fa": "بازدم هنگام پایین بردن.",
        "breathing_guide_en": "Exhale on the pushdown.",
        "injury_contraindications": ["wrist", "elbow"],
        "equipment_needed_fa": "دستگاه سیم‌کش",
        "equipment_needed_en": "Cable machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "اسکوات با هالتر",
        "name_en": "Barbell Back Squat",
        "target_muscle_fa": "چهارسر، باسن، همسترینگ",
        "target_muscle_en": "Quads, glutes, hamstrings",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر خنثی؛ زانو هم‌راستا با پنجه.",
        "execution_tips_en": "Neutral spine; knees track over toes.",
        "breathing_guide_fa": "دم قبل از پایین رفتن، بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Inhale before descent, exhale on ascent.",
        "injury_contraindications": ["knee", "lower_back"],
        "equipment_needed_fa": "هالتر و رک",
        "equipment_needed_en": "Barbell and rack",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "ددلیفت",
        "name_en": "Deadlift",
        "target_muscle_fa": "پشت، باسن، همسترینگ",
        "target_muscle_en": "Back, glutes, hamstrings",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر خنثی؛ حرکت از لگن.",
        "execution_tips_en": "Neutral spine; hinge from hips.",
        "breathing_guide_fa": "دم قبل از بلند کردن، بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Inhale before lift, exhale up.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "هالتر",
        "equipment_needed_en": "Barbell",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "هیپ تراست",
        "name_en": "Hip Thrust",
        "target_muscle_fa": "باسن",
        "target_muscle_en": "Glutes",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "چانه پایین؛ در بالا باسن را منقبض کنید.",
        "execution_tips_en": "Chin tucked; squeeze glutes at top.",
        "breathing_guide_fa": "بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Exhale on the lift.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "هالتر و نیمکت",
        "equipment_needed_en": "Barbell and bench",
    },
    {
        "category": "functional_home",
        "name_fa": "پل باسن",
        "name_en": "Glute Bridge",
        "target_muscle_fa": "باسن، همسترینگ",
        "target_muscle_en": "Glutes, hamstrings",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر را قوس ندهید؛ بالا مکث کنید.",
        "execution_tips_en": "Avoid arching; pause at the top.",
        "breathing_guide_fa": "بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Exhale on the lift.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "سوپرمن",
        "name_en": "Superman",
        "target_muscle_fa": "پشت، باسن",
        "target_muscle_en": "Back, glutes",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت آرام و با کنترل انجام شود.",
        "execution_tips_en": "Slow, controlled movement.",
        "breathing_guide_fa": "بازدم هنگام بالا آوردن دست و پا.",
        "breathing_guide_en": "Exhale as you lift.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "ددباگ",
        "name_en": "Dead Bug",
        "target_muscle_fa": "عضلات مرکزی",
        "target_muscle_en": "Core",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر به زمین؛ حرکت دست و پای مخالف.",
        "execution_tips_en": "Lower back on floor; opposite arm/leg.",
        "breathing_guide_fa": "بازدم هنگام دراز کردن دست و پا.",
        "breathing_guide_en": "Exhale as you extend.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "پرش پروانه",
        "name_en": "Jumping Jacks",
        "target_muscle_fa": "تمام بدن",
        "target_muscle_en": "Full body",
        "level": "beginner",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "فرود نرم؛ ریتم ثابت.",
        "execution_tips_en": "Soft landing; steady rhythm.",
        "breathing_guide_fa": "تنفس ریتمیک.",
        "breathing_guide_en": "Rhythmic breathing.",
        "injury_contraindications": ["ankle", "knee"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "طناب زدن",
        "name_en": "Jump Rope",
        "target_muscle_fa": "ساق، قلبی-عروقی",
        "target_muscle_en": "Calves, cardio",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "پرش کوتاه؛ مچ فعال.",
        "execution_tips_en": "Small jumps; active wrists.",
        "breathing_guide_fa": "تنفس منظم.",
        "breathing_guide_en": "Steady breathing.",
        "injury_contraindications": ["ankle", "knee"],
        "equipment_needed_fa": "طناب",
        "equipment_needed_en": "Jump rope",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "دوچرخه ثابت",
        "name_en": "Stationary Bike",
        "target_muscle_fa": "چهارسر، قلبی-عروقی",
        "target_muscle_en": "Quads, cardio",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "زانوها هم‌راستا با پنجه‌ها.",
        "execution_tips_en": "Knees aligned with toes.",
        "breathing_guide_fa": "تنفس ریتمیک.",
        "breathing_guide_en": "Rhythmic breathing.",
        "injury_contraindications": ["knee"],
        "equipment_needed_fa": "دوچرخه ثابت",
        "equipment_needed_en": "Stationary bike",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پرس سینه هالتر",
        "name_en": "Barbell Bench Press",
        "target_muscle_fa": "سینه، شانه، پشت بازو",
        "target_muscle_en": "Chest, shoulders, triceps",
        "level": "intermediate",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "پاها ثابت؛ تیغه‌های کتف جمع.",
        "execution_tips_en": "Feet planted; retract shoulder blades.",
        "breathing_guide_fa": "دم پایین، بازدم بالا.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "هالتر و نیمکت",
        "equipment_needed_en": "Barbell and bench",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پرس سرشانه دمبل نشسته",
        "name_en": "Seated Dumbbell Shoulder Press",
        "target_muscle_fa": "شانه، سه‌سر",
        "target_muscle_en": "Shoulders, triceps",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر تکیه داده؛ حرکت عمودی.",
        "execution_tips_en": "Back supported; press vertically.",
        "breathing_guide_fa": "بازدم هنگام فشار.",
        "breathing_guide_en": "Exhale on press.",
        "injury_contraindications": ["shoulder", "neck"],
        "equipment_needed_fa": "دمبل و نیمکت",
        "equipment_needed_en": "Dumbbells and bench",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "نشر جانب",
        "name_en": "Lateral Raise",
        "target_muscle_fa": "سرشانه کناری",
        "target_muscle_en": "Lateral deltoid",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "آرنج کمی خم؛ بالا تا هم‌سطح شانه.",
        "execution_tips_en": "Slight elbow bend; raise to shoulder level.",
        "breathing_guide_fa": "بازدم هنگام بالا آوردن.",
        "breathing_guide_en": "Exhale as you lift.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "دمبل",
        "equipment_needed_en": "Dumbbells",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "کیک‌بک پشت بازو",
        "name_en": "Triceps Kickback",
        "target_muscle_fa": "پشت بازو",
        "target_muscle_en": "Triceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "آرنج ثابت؛ فقط ساعد حرکت کند.",
        "execution_tips_en": "Keep elbow fixed; move forearm only.",
        "breathing_guide_fa": "بازدم هنگام صاف کردن.",
        "breathing_guide_en": "Exhale on extension.",
        "injury_contraindications": ["wrist"],
        "equipment_needed_fa": "دمبل",
        "equipment_needed_en": "Dumbbell",
    },
    {
        "category": "functional_home",
        "name_fa": "کرانچ",
        "name_en": "Crunch",
        "target_muscle_fa": "شکم",
        "target_muscle_en": "Abs",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "گردن را نکشید؛ چانه به سمت بالا.",
        "execution_tips_en": "Do not pull the neck; keep chin up.",
        "breathing_guide_fa": "بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Exhale on the lift.",
        "injury_contraindications": ["neck"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "پلانک بغل",
        "name_en": "Side Plank",
        "target_muscle_fa": "عضلات مرکزی، مورب شکم",
        "target_muscle_en": "Core, obliques",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "بدن در یک خط؛ لگن پایین نیاید.",
        "execution_tips_en": "Keep body aligned; avoid hip drop.",
        "breathing_guide_fa": "تنفس آرام و منظم.",
        "breathing_guide_en": "Slow, steady breathing.",
        "injury_contraindications": ["wrist", "shoulder"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "اسکوات جام",
        "name_en": "Goblet Squat",
        "target_muscle_fa": "چهارسر، باسن",
        "target_muscle_en": "Quads, glutes",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "وزنه نزدیک سینه؛ زانو هم‌راستا با پنجه.",
        "execution_tips_en": "Hold weight close; knees track toes.",
        "breathing_guide_fa": "دم پایین، بازدم بالا.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["knee", "lower_back"],
        "equipment_needed_fa": "کتل‌بل یا دمبل",
        "equipment_needed_en": "Kettlebell or dumbbell",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "اسلم توپ مدیسن",
        "name_en": "Medicine Ball Slam",
        "target_muscle_fa": "تمام بدن",
        "target_muscle_en": "Full body",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "هسته بدن درگیر؛ حرکت انفجاری کنترل‌شده.",
        "execution_tips_en": "Engage core; controlled explosive slam.",
        "breathing_guide_fa": "بازدم هنگام ضربه.",
        "breathing_guide_en": "Exhale on the slam.",
        "injury_contraindications": ["shoulder", "lower_back"],
        "equipment_needed_fa": "توپ مدیسن",
        "equipment_needed_en": "Medicine ball",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پشت پا خوابیده",
        "name_en": "Lying Leg Curl",
        "target_muscle_fa": "همسترینگ",
        "target_muscle_en": "Hamstrings",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "لگن ثابت؛ حرکت آرام.",
        "execution_tips_en": "Keep hips down; slow movement.",
        "breathing_guide_fa": "بازدم هنگام جمع کردن.",
        "breathing_guide_en": "Exhale as you curl.",
        "injury_contraindications": ["knee"],
        "equipment_needed_fa": "دستگاه پشت پا",
        "equipment_needed_en": "Leg curl machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "ساق پا ایستاده",
        "name_en": "Standing Calf Raise",
        "target_muscle_fa": "ساق",
        "target_muscle_en": "Calves",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت کامل از پاشنه تا نوک پا.",
        "execution_tips_en": "Full range from heel to toe.",
        "breathing_guide_fa": "بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Exhale on lift.",
        "injury_contraindications": ["ankle"],
        "equipment_needed_fa": "دستگاه ساق پا",
        "equipment_needed_en": "Calf raise machine",
    },
    {
        "category": "functional_home",
        "name_fa": "اسکوات دیواری",
        "name_en": "Wall Sit",
        "target_muscle_fa": "چهارسر",
        "target_muscle_en": "Quads",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر به دیوار؛ زاویه زانو ۹۰ درجه.",
        "execution_tips_en": "Back to wall; knees at 90 degrees.",
        "breathing_guide_fa": "تنفس آرام و منظم.",
        "breathing_guide_en": "Slow steady breathing.",
        "injury_contraindications": ["knee"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "پرش اسکوات",
        "name_en": "Jump Squat",
        "target_muscle_fa": "چهارسر، باسن",
        "target_muscle_en": "Quads, glutes",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "فرود نرم؛ زانو هم‌راستا.",
        "execution_tips_en": "Soft landing; knees aligned.",
        "breathing_guide_fa": "بازدم هنگام پرش.",
        "breathing_guide_en": "Exhale on jump.",
        "injury_contraindications": ["knee", "ankle"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "راور",
        "name_en": "Rowing Machine",
        "target_muscle_fa": "پشت، پاها، قلبی-عروقی",
        "target_muscle_en": "Back, legs, cardio",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت با پا شروع شود؛ سپس دست‌ها.",
        "execution_tips_en": "Drive with legs first, then arms.",
        "breathing_guide_fa": "دم هنگام بازگشت، بازدم هنگام کشیدن.",
        "breathing_guide_en": "Inhale on return, exhale on pull.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "دستگاه روئینگ",
        "equipment_needed_en": "Rowing machine",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "دویدن روی تردمیل",
        "name_en": "Treadmill Run",
        "target_muscle_fa": "قلبی-عروقی، پاها",
        "target_muscle_en": "Cardio, legs",
        "level": "beginner",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "گام‌های کوتاه؛ وضعیت بدن صاف.",
        "execution_tips_en": "Short steps; upright posture.",
        "breathing_guide_fa": "تنفس ریتمیک.",
        "breathing_guide_en": "Rhythmic breathing.",
        "injury_contraindications": ["knee", "ankle"],
        "equipment_needed_fa": "تردمیل",
        "equipment_needed_en": "Treadmill",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پرس بالا سینه دمبل",
        "name_en": "Incline Dumbbell Press",
        "target_muscle_fa": "بالاسینه، شانه",
        "target_muscle_en": "Upper chest, shoulders",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "زاویه نیمکت ۳۰ تا ۴۵ درجه.",
        "execution_tips_en": "Bench angle 30–45 degrees.",
        "breathing_guide_fa": "دم پایین، بازدم بالا.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "دمبل و نیمکت شیب‌دار",
        "equipment_needed_en": "Dumbbells and incline bench",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "فلای سیم‌کش",
        "name_en": "Cable Fly",
        "target_muscle_fa": "سینه",
        "target_muscle_en": "Chest",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "کمی خمیدگی آرنج؛ حرکت قوسی.",
        "execution_tips_en": "Slight elbow bend; arc motion.",
        "breathing_guide_fa": "بازدم هنگام جمع کردن.",
        "breathing_guide_en": "Exhale as you bring arms together.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "دستگاه سیم‌کش",
        "equipment_needed_en": "Cable machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "بارفیکس",
        "name_en": "Pull-up",
        "target_muscle_fa": "پشت، زیر بغل",
        "target_muscle_en": "Back, lats",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "بدن ثابت؛ چانه بالای میله.",
        "execution_tips_en": "Keep body stable; chin above bar.",
        "breathing_guide_fa": "بازدم هنگام بالا رفتن.",
        "breathing_guide_en": "Exhale on the pull.",
        "injury_contraindications": ["shoulder", "elbow"],
        "equipment_needed_fa": "میله بارفیکس",
        "equipment_needed_en": "Pull-up bar",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "تی‌بار رو",
        "name_en": "T-Bar Row",
        "target_muscle_fa": "پشت، زیر بغل",
        "target_muscle_en": "Back, lats",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "کمر خنثی؛ آرنج‌ها نزدیک بدن.",
        "execution_tips_en": "Neutral spine; elbows close.",
        "breathing_guide_fa": "بازدم هنگام کشیدن.",
        "breathing_guide_en": "Exhale on pull.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "تی‌بار",
        "equipment_needed_en": "T-bar",
    },
    {
        "category": "functional_home",
        "name_fa": "کوه‌نورد",
        "name_en": "Mountain Climbers",
        "target_muscle_fa": "مرکزی، قلبی-عروقی",
        "target_muscle_en": "Core, cardio",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "ریتم ثابت؛ لگن پایین.",
        "execution_tips_en": "Steady rhythm; hips low.",
        "breathing_guide_fa": "تنفس سریع اما کنترل‌شده.",
        "breathing_guide_en": "Fast but controlled breathing.",
        "injury_contraindications": ["wrist", "shoulder"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "functional_home",
        "name_fa": "اسکوات بلغاری",
        "name_en": "Bulgarian Split Squat",
        "target_muscle_fa": "چهارسر، باسن",
        "target_muscle_en": "Quads, glutes",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "گام ثابت؛ زانو هم‌راستا.",
        "execution_tips_en": "Stable stance; knee aligned.",
        "breathing_guide_fa": "دم پایین، بازدم بالا.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["knee", "ankle"],
        "equipment_needed_fa": "نیمکت",
        "equipment_needed_en": "Bench",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "اسپرینت دوچرخه",
        "name_en": "Bike Sprint",
        "target_muscle_fa": "قلبی-عروقی، پاها",
        "target_muscle_en": "Cardio, legs",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "شدت بالا در بازه کوتاه.",
        "execution_tips_en": "High intensity for short intervals.",
        "breathing_guide_fa": "بازدم هنگام شدت بالا.",
        "breathing_guide_en": "Exhale during hard effort.",
        "injury_contraindications": ["knee"],
        "equipment_needed_fa": "دوچرخه ثابت",
        "equipment_needed_en": "Stationary bike",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "جلوبازو سیم‌کش",
        "name_en": "Cable Curl",
        "target_muscle_fa": "جلو بازو",
        "target_muscle_en": "Biceps",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "آرنج ثابت؛ حرکت کنترل‌شده.",
        "execution_tips_en": "Elbows fixed; controlled motion.",
        "breathing_guide_fa": "بازدم هنگام بالا آوردن.",
        "breathing_guide_en": "Exhale on curl.",
        "injury_contraindications": ["wrist"],
        "equipment_needed_fa": "دستگاه سیم‌کش",
        "equipment_needed_en": "Cable machine",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "پشت بازو دیپ",
        "name_en": "Triceps Dip",
        "target_muscle_fa": "پشت بازو، سینه",
        "target_muscle_en": "Triceps, chest",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "بدن را کنترل کنید؛ دامنه مناسب.",
        "execution_tips_en": "Control the body; proper depth.",
        "breathing_guide_fa": "بازدم هنگام بالا آمدن.",
        "breathing_guide_en": "Exhale on push up.",
        "injury_contraindications": ["shoulder", "wrist"],
        "equipment_needed_fa": "میله دیپ",
        "equipment_needed_en": "Dip bars",
    },
    {
        "category": "functional_home",
        "name_fa": "لانژ جانبی",
        "name_en": "Lateral Lunge",
        "target_muscle_fa": "داخل ران، باسن",
        "target_muscle_en": "Adductors, glutes",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "وزن روی پای خم؛ پای دیگر صاف.",
        "execution_tips_en": "Shift weight to bent leg; other leg straight.",
        "breathing_guide_fa": "دم پایین، بازدم بالا.",
        "breathing_guide_en": "Inhale down, exhale up.",
        "injury_contraindications": ["knee", "ankle"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "سکشن حمل کتل‌بل",
        "name_en": "Farmer's Carry",
        "target_muscle_fa": "هسته بدن، ساعد",
        "target_muscle_en": "Core, forearms",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "شانه‌ها عقب؛ بدن صاف.",
        "execution_tips_en": "Shoulders back; tall posture.",
        "breathing_guide_fa": "تنفس آرام.",
        "breathing_guide_en": "Steady breathing.",
        "injury_contraindications": ["lower_back"],
        "equipment_needed_fa": "کتل‌بل یا دمبل",
        "equipment_needed_en": "Kettlebells or dumbbells",
    },
    {
        "category": "bodybuilding_machine",
        "name_fa": "کراس اور",
        "name_en": "Cable Crossover",
        "target_muscle_fa": "سینه",
        "target_muscle_en": "Chest",
        "level": "intermediate",
        "intensity": "medium",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت قوسی؛ کتف ثابت.",
        "execution_tips_en": "Arc motion; keep shoulders stable.",
        "breathing_guide_fa": "بازدم هنگام جمع کردن.",
        "breathing_guide_en": "Exhale as you bring arms together.",
        "injury_contraindications": ["shoulder"],
        "equipment_needed_fa": "دستگاه سیم‌کش",
        "equipment_needed_en": "Cable machine",
    },
    {
        "category": "functional_home",
        "name_fa": "پرش از طناب خیالی",
        "name_en": "Shadow Jump Rope",
        "target_muscle_fa": "ساق، قلبی-عروقی",
        "target_muscle_en": "Calves, cardio",
        "level": "beginner",
        "intensity": "light",
        "gender_suitability": "both",
        "execution_tips_fa": "پرش کوتاه و ریتمیک.",
        "execution_tips_en": "Small rhythmic hops.",
        "breathing_guide_fa": "تنفس ریتمیک.",
        "breathing_guide_en": "Rhythmic breathing.",
        "injury_contraindications": ["ankle"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
    {
        "category": "hybrid_hiit_machine",
        "name_fa": "شنا قدرتی",
        "name_en": "Power Push-up",
        "target_muscle_fa": "سینه، شانه، پشت بازو",
        "target_muscle_en": "Chest, shoulders, triceps",
        "level": "advanced",
        "intensity": "heavy",
        "gender_suitability": "both",
        "execution_tips_fa": "حرکت انفجاری؛ کنترل فرود.",
        "execution_tips_en": "Explosive push; controlled landing.",
        "breathing_guide_fa": "بازدم هنگام پرتاب.",
        "breathing_guide_en": "Exhale on explosive push.",
        "injury_contraindications": ["wrist", "shoulder"],
        "equipment_needed_fa": "بدون تجهیزات",
        "equipment_needed_en": "No equipment",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        added = 0
        for item in SEED_EXERCISES:
            exists = Exercise.query.filter_by(name_en=item["name_en"]).first()
            if exists:
                continue
            exercise = Exercise(
                category=item["category"],
                name_fa=item["name_fa"],
                name_en=item["name_en"],
                target_muscle_fa=item["target_muscle_fa"],
                target_muscle_en=item["target_muscle_en"],
                level=item["level"],
                intensity=item["intensity"],
                gender_suitability=item["gender_suitability"],
                execution_tips_fa=item["execution_tips_fa"],
                execution_tips_en=item["execution_tips_en"],
                breathing_guide_fa=item["breathing_guide_fa"],
                breathing_guide_en=item["breathing_guide_en"],
                injury_contraindications=json.dumps(item["injury_contraindications"], ensure_ascii=False),
                equipment_needed_fa=item["equipment_needed_fa"],
                equipment_needed_en=item["equipment_needed_en"],
            )
            db.session.add(exercise)
            added += 1
        db.session.commit()
        print(f"Seeded {added} exercises.")


if __name__ == "__main__":
    seed()
